                <blockquote>
			<a name="introduction"></a>
			<p class="Heading">Introduction</p>
			<p align="justify"><b>F</b>amous for  ‘peg’, ‘pagri’, ‘paranda’ (tasselled tag for braiding hair and ‘Jutti’ (footwear), joyous buoyance, royal demeanor, sensuous and graceful feminine gait and </p>
			
			<p align="justify">Aristocracy, Patiala presents a beautiful bouquet of life-style even to a casual visitor to the city. A brilliant spectrum of Rajput, Mughal and Punjabi cultures, a fine blend of modernity and  tradition and a judicious synthesis of all that is beautiful in form and bold in spirit conjure up&gt; a vision called 'Patiala'.</p>
			<p align="justify">Patiala, an erstwhile princely state, capital of PEPSU and a district headquarters of Punjab are situated in the Malwa region of Punjab. Malwa has the largest number Of districts in&nbsp;the reorganised Punjab, and antiquity of some of the cities goes back to the ancient and early medieval period. Patiala is relatively a young city, a few years more than two centuries old. </p>
			
			
			<p align="justify">In the 18<sup>th</sup> century, the political vacuum created by the downfall of the Mughals was successfully filled up by the Sikh <img src="../images/image001.jpg" align="left" alt="Baba Ala Singh" width="144" height="169" data-pin-nopin="true">Misldars in Punjab by thwarting the designs of both the Marathas and the Afghans. One among these independent principalities of the Sikhs was that established by Baba Ala Singh at Patiala.</p>
			<p align="justify">The early history of the founders of Patiala state is more of a myth mystery than reality. The rulers of the erstwhile states of Patiala, Nabha and Jind trace their ancestry to one Chaudhary Phul. Apparently the appellation of dynasty 'Phulkian' is derived from their common founder. One of his sons, Chaudhary Ram Singh was baptised and blessed by Guru Gobind Singh. His son Ala Singh assumed the leadership in 1714 A.D. when Banda Bahadur was engaged in the fierce struggle against the Mughals. A man with vision and courage, Ala Singh carved out an independent principality from a petty Zamindari of 30 villages. Under his successors, it expanded into a big State, touching the Shivaliks in north, Rajasthan in the south and upper courses of the Jamuna and the Sutlej. While confronting the most trying and&nbsp; challenging&nbsp; circumstances in the middle eighteenth century, Baba Ala Singh, unlike many of his contemporaries, displayed tremendous courage and shrewdness in dealing with the Mughals, Afghans and Marathas, and successfully established and maintained a state which he had started building up bit by bit from its nucleus Barnala. In 1763 Baba Ala Singh laid the foundation of the Patiala fort known as Qila Mubarak, around 'which the present city of Patiala is built. </p>
			
			<p align="justify">After the third Battle of Panipat in 1761 in which the Marathas were defeated, the writ of the Afghans prevailed throughout Punjab.<img src="../images/Image52.jpg" align="right" alt="" width="233" height="157"> It is at this stage that the rulers of Patiala began to acquire ensigns of royalty. Ahmad Shah Abdali bestowed upon Ala Singh drum and banner after latter's death, his grandson Amar Singh, succeeded and received the title of Raja-i-Rajgan. He was also allowed to strike coins, After forty years of ceaseless struggle with the Mughals, Afghans and Marathas, the borders of the Patiala state witnessed the trailing blaze of Ranjit Singh in the north and that of the British in the east. Bestowed with the gift and instinct of survival, and of making right choice at the right time, the Raja of Patiala entered into a treaty with the British against Ranjit Singh in 1808, thus becoming collaborator in the grand empire building process by the British in, the sub-continent of India. The rulers of Patiala such as Karam Singh, Narinder Singh, Mahendra Singh, Rajinder Singh, Bhupinder Singh and Yadvindra Singh were treated with respect and dignity by the British.</p>
			
			<p align="justify">It was Maharaja Bhupinder Singh (1900-1930) who gave the Patiala state a prominent place on the political map of India and, in the field of international sports.<img src="../images/image003.gif" alt="Maharaja Bhupinder Singh" align="left" width="95" height="150"> Most of the&nbsp;buildings with splendid architectural designs were constructed during his reign. His son Yadvindra Singh was among those Indian princes who, readily came forward to sign the Instrument of Accession, thus&nbsp;facilitating the process of national integration. In recognition of his services, he was appointed the&nbsp;Rajpramukh of the newly established state of PEPSU. Eulogizing his role of the Maharaja in fighting against the intrigues and manoeuvres of the unfriendly and hostile princes of India, Sardar Vallabh Bhai Patel the then Deputy Prime Minister and in charge of Home Affairs Ministry remarked :"1 must mention the notable contribution which His Highness, the Maharaja of Patiala, has made to the unity and integrity of India. He took the cause of the country at a time when there were few friends amongst the princely order and when serious attempts were being made to balkanize India. It was his patriotic lead that contributed in a large measure, to a change in the attitude of the princes to the problem of accession to the Indian&nbsp;Dominion."</p>
			
			<p align="justify">Though historians have tried to trace the origin of Patiala (as far as the name is concerned) to Rig Vedic literature yet the town as it stands today was founded by Ala Singh with the construction of the Qila&nbsp;Mubarak in the year 1763. One gets the impression as if the city was designed and developed according to a plan akin to that of temple architecture. In the heart of the city was the seat of the king similar to the house of the deity and the residential areas of communities developed almost status-wise. Close to Qila Mubarak were the Mohallas of the Khatris, Aroras, Baniyas along with the big Havelis of the nobility, The first settlers of Patiala were the Hindus of Sirhind, who opened their business establishments outside the Darshani Gate. The lower caste got settled on the peripheral areas of the Patiala city now known as Chur Majris. As in all the medieval towns, there were separate localities of dancing girls. Dharampura Bazar was one such in Patiala, which was frequented by the ruling elite. In the late nineteenth century, the ruling class having been granted huge Jagirs became rich and started constructing huge mansions with sprawling lawns. Some of the buildings though shabbily maintained, stand as mute evidence of that feudal glory. Maharaja Narendra Singh (1845-1862) fortified the city of Patiala by constructing ramparts and ten gates around the city. Some of these gates have been demolished to facilitate the flow of traffic. Inside the walls, besides the residences, there are Mandis and Bazars and a visitor with meagre amount in his pocket can still indulge in the luxury of purchasing traditional goods famous for their art and beauty such as embroidered Juti and Phulkari.</p>
			
			<a name="culture"></a>
			<p class="Heading">Culture &amp; Traditions</p>
			<p align="justify"><b>P</b>atiala's sway over the Malwa area extended beyond merely political influence. Patiala was equally the set of religious and cultural life. Educationally, Patiala was in the forefront. Patiala was the first town in this part of the country to have Degree Collage-the Mohindra College-in 1870. The famous printing of Munshi Nawal Kishore was also established here in the seventies of the 19th century. Patiala has had a culture of its own, evolving into a distinct "patialavi" culture. Patiala has also seen evolution of a distinct style of architecture. Borrowing from the Rajput Style, its beauty and elegance are, however, moulded according to the local coloring.</p>
			
			<p align="justify">With the active patronage of the erstwhile rules of Patiala, a well established style of Hindustani  music called ‘the Patiala Gharana’ came into existence and has held its own up to the present times. This school of music has had a number of famous musicians, many of whom came to Patiala after the disintegration of the Mughal Court at Delhi in the 18<sup>th</sup> century. At the turn of the century, Ustad Ali Bux was the most renowned exponent of this Gharana. Later his sons, Ustad Akhtar Hussain Khan and Ustad Bade Ghulam Ali Khan achieved world wide fame and brought glory to the Patiala Gharana. This school of music continues to get the patronage of the State though the North-Zone Culture Centre, established at Patiala.</p>
			
			<a name="architecture"></a>
			<p class="Heading">Architecture</p>

			<ul>
				<li><p align="justify">Qila Mubarak</p></li><p></p>
				<li><p align="justify">Moti Bagh Palace</p></li><p></p>
				<li><p align="justify">Sheesh Mahal and Museum</p></li><p></p>
				<li><p align="justify">Government Mohindra College</p></li><p></p>
				<li><p align="justify">Baradari Gardens</p></li><p></p>
				<li><p align="justify">Bahadurgarh Fort</p></li><p></p>
			</ul>

		
			<p align="justify"><b>Qila Mubarak</b></p>
			
			<p align="justify"><b>T</b>he Qila Mubarak was first developed as a mud fort or Kachi Garhi. Baba Ala Singh constructed the Pacca Qila after his conquest of Sirhind. From the receipts of <img src="../images/Image45.gif" alt="Qila Mubarak" align="right" width="300" height="180">the octroi on the merchandise passing through his territory of the G.T. road, he constructed the Qila. The present Qila is divided into two parts- one, the Qila Androon, the interior portion, was built by Ala Singh. Situated on a mound, it ascends as one moves into it. While the other i.e., between the Qila Androon and outer walls with the secretariat on the left and Darbar Hall on the right, was built by Maharaja Karam Singh. The Darbar Hall is now converted into a mini museum where  rare arms and armours including a sword of Nadir Shah known as 'Shikar Gah' are on display. Most precious pieces of art are the rich collection of tree-like chandeliers made of Bohemian cut-glass emitting prism like radiant splendour and sheen. To those interested in metallurgy and guns, a visit to the Cannon Park within the premises of the Qila Mubarak would certainly be a thrilling experience of life time. The murals inside the palaces are rare specimen of the Kangra and Rajasthan paintings. </p>
			
			<p align="justify"><b>Moti Bagh Palace</b></p>
			<p align="justify"><b>T</b>he next great architectural landmark is the Moti Bagh Palace constructed in 1847 by Maharaja Narendra Singh at a cost of Rs. 5 lakhs; Maharaja Narendra Singh was as great a builder as Swai Jai Singh of Jaipur. The Moti Bagh Palace was designed on the pattern of Shalimar Gardens of Lahore with terraces, water channels,<img src="../images/Image46.jpg" alt="Moti Bagh Palace" align="left" width="233" height="154"> Sheesh Mahal and beautiful garden. It is a four storeyed structure with massive stone-walls, arched openings, filtered and ornamental grills and crowning domes. </p>
			
			<p align="justify">The rear part of the palace has been developed into an amusement park, which offers many attractions to the young and the old alike. In the foreground of the Sheesh Mahal, there is a huge tank with two towers on both sides. Along with it is the suspended rope bridge popularly known as Lakshman Jhula, which connects the palace with the Bansar Ghar housing the Natural History Gallery. Here the stuffed animals and birds are displayed. The rest of the palace now houses the most prestigious Subhash Chander Bose National Institute of Sports.</p>
			
			
			<p align="justify"><b>Sheesh Mahal and Museum</b></p>
			<p align="justify"><b>M</b>aharaja Narendra Singh was a great patron of literature, music and fine arts. He invited many painters from Kangra and Rajasthan to paint the walls of Sheesh Mahal. Their works depicting the vision in poetry of Keshav, Surdas and Bihari, both in line and colour, are a treat to the eye of the beholder. The themes of these paintings embrace mythology, legends, Raga-Ragni, Nayak-Nayika and Bara-masa in Rajasthani style. These walls and ceilings are also rich in floral designs. <img src="../images/Image47.jpg" alt="Sheesh Mahal and Museum" align="right" width="165" height="121"> The interior casts a&nbsp;Kaleidoscope phantasmagoria of myriad images and multi-coloured lights. The museum has a rich collection of miniature paintings of the middle of 19th century. Themes of these paintings are based on the Geet Gobinda or Jaya Deva's poetry. The Kangra paintings depicting the, Krishan Lila reflect the highest professional and delicate taste. Paintings displaying the Raga-mala of the Rajasthan schools and that of the Mughal give a visual meaning to the Ragas.</p>

			<p align="justify">Besides miniature paintings, there are fine objects of Tibetan art particularly the sculpture of different kinds of metals. Ivory carvings of Punjab, royal wooden carved furniture, and a large number of Burmese and Kashmiri carved objects are also exhibited. One can see the huge portraits of the rulers of Patiala adorning the walls of museum hall. Some of the rare manuscripts can be seen here. Beside Janamsakhi and Jain&nbsp;manuscripts, the most valuable possession is the Gulistan-Bostan by Sheikh Sadi of Shiraz, which was acquired by the Mughal Emperor Shah Jahan for his personal library.</p>
			<p align="justify">Medal Gallery set up in the Sheesh Mahal has on display the largest number of medals and decorations in the world, numbering 3,200. Collected by Maharaja Bhupinder Singh from all over the world, his illustrious son Maharaja Yadvindra Singh gifted the entire priceless collection to the Punjab Government Museum. Among the most important, one may mention The Order of the Garter (England) of 1348 A.D., The Order of the Golden Fleece (Austria) founded in 1430 A.D. The Order of St. Andrews (Russia) founded in 1688 by Peter the Great; The Order of the Rising Sun (Japan) and Order of the Double Dragon (China) and The Order of the White Elephant (Thailand). The collection contains medals from Belgium, Denmark, Finland and host of other countries of Africa and Asia.</p>
			<p align="justify">On the advice of the Europeans, Maharaja Ranjit Singh and Maharaja Dalip Singh also issued medals&nbsp;which are studded with precious stones. Some of them display miniature paintings of the Maharaja in profile in the centre. Inspired by his hobby, Maharaja Bhupinder Singh instituted Orders and Decorations which carry portraits of Guru Gobind Singh, Radha Krishan etc. These medals reflect religion, culture and art of many countries in metal and are great sources of history.</p>
			<p align="justify">Besides medals, there is a rare collection of coins. This numismatic collection presents a vast range from the punch-marked coins to those issued by the princely states in the 19th century. It is a total numismatic history reflecting upon country's trade, commerce, science and metallurgy.</p>
			
			<p align="justify"><b>Government Mohindra College</b></p>
			<p align="justify"><b>M</b>aharaja <img src="../images/Mohindra College -2.gif" alt="Government Mohindra College" align="left" width="220" height="150">Mahendra Singh was a great patron of modern education. He established this college in 1870 for the people of Patiala. Its building is a wonderful piece of architecture. Famous for its architectural excellence, the institution for a long time was the only one between Delhi and Lahore. Serving as a major institution of higher education, many students from neighbouring states and as far as Delhi used to come to Patiala for receiving education.</p>
			<p align="justify"><b>Baradari Gardens</b></p>
			<p align="justify"><b>S</b>ituated in the north of the old Patiala city, just outside the Sheranwala Gate, the Baradari Gardens is built around the Baradari Palace constructed as a residence for the crown Prince Rajinder Singh. A great lover of nature, the crown <img src="../images/Image49.gif" alt="Baradari Gardens" align="right" width="303" height="154">Prince brought all kinds of saplings of rare trees and planted them here in the garden. The huge fruit trees, the Fern House and the Rock Garden stand testimony to his interest. The Baradari Palace now houses the Punjab State Archives, a repository of rare documents of historical importance.</p>
			
			<p align="justify"><b>Bahadurgarh Fort</b></p>			
			<p align="justify"><b>A</b>t a distance of one and half kilometer from the main gate of Punjabi University, It is named so to commemorate the holy memory of Guru Tegh Bahadur who paid visit to this place at the invitation of another holy person Saif Khan. The four wails of the fort enclose the village Saifabad located on the left-side of the Rajpura-Patiala Road. Saif Khan, a relative of the Mughal Emperor Aurangzeb, after holding several important offices, became a hermit and settled down here. After his death he was buried here. His tomb behind the fort, a structure of 177 x 177 ft. is in a state of neglect. Notwithstanding this, his followers still lit a lamp on the tomb every Thursday. The two inscriptions in the fort testify that the village and the mosque were founded in 1668 during the reign of Aurangzeb. <img src="../images/Image50.jpg" align="left" alt="Bahadurgarh Fort" width="157" height="100">As the tradition goes, Nawab Saif Khan was a great admirer of Guru Teg Bahadur. He invited him to spend rainy season here. His visit is commemorated by two gurdwaras- One inside the fort and the other outside across the road. It is famous as Panj Bali Gurdwara.The Bahadurgarh Fort was constructed by Maharaja Karam Singh during 1837-45 at a cost of Rs. 10, 00,000. Its circumference is one mile, 536 yards and 2 feet.</p>
			
			<!--  Page Contents Ends Here -->	
		
		</blockquote>
		